meta_product_name: "Soundmates"
meta_title: "Soundmates - Find your fellow creatives"
meta_description: "Connect and collaborate with your fellow music creatives to find your next soundmate !"
meta_image: "background-image-index.png" # should exist in `app/assets/images/`
